### PR TITLE
[WIP] Removing samples

### PR DESCRIPTION
**Pull request by calumgunn**
Hey all,

I (and I'm sure you) think that it's a good idea to trim this repo of samples which are either inappropriate or unnecessary.

Get your removals in!

### CODE REVIEW

**Review by don-smith — APPROVED** [review]
LGTM!

**Comment by telephon** [comment]
ready to merge?

**Comment by yaxu** [comment]
Oops sorry this took a while, thanks all!

**Comment by telephon** [comment]
@yaxu no problem, just wanted to ask!

**Pull request merged**
